use_frameworks!

target 'ZCFirstCocoapodsProject_Example' do
  pod 'ZCFirstCocoapodsProject', :path => '../'

  target 'ZCFirstCocoapodsProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
